# Generated by Django 5.1.7 on 2025-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Общее', max_length=100),
        ),
    ]
